version: '3.7'

services:
  app:
    build: .
    depends_on:
      - mongodb_container

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: